const ProfileActionTypes = {
  FETCH_USER_PROFILE_START: 'FETCH_USER_PROFILE_START',
  FETCH_USER_PROFILE_SUCCESS: 'FETCH_USER_PROFILE_SUCCESS',
  FETCH_USER_PROFILE_FAILURE: 'FETCH_USER_PROFILE_SUCCESS',
  FETCH_WHO_TO_FOLLOW_START: 'FETCH_WHO_TO_FOLLOW_START',
  FETCH_WHO_TO_FOLLOW_SUCCESS: 'FETCH_WHO_TO_FOLLOW_SUCCESS',
  FETCH_WHO_TO_FOLLOW_FAILURE: 'FETCH_WHO_TO_FOLLOW_FAILURE',
  FOLLOW_USER_START: 'FOLLOW_USER_START',
  FOLLOW_USER_SUCCESS: 'FOLLOW_USER_SUCCESS',
  FOLLOW_USER_FAILURE: 'FOLLOW_USER_FAILURE',
  UNFOLLOW_USER_START: 'UNFOLLOW_USER_START',
  UNFOLLOW_USER_SUCCESS: 'UNFOLLOW_USER_SUCCESS',
  UNFOLLOW_USER_FAILURE: 'UNFOLLOW_USER_FAILURE',
};

export default ProfileActionTypes;
