const PostActionTypes = {
  CREATE_POST_START: 'CREATE_POST_START',
  CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
  CREATE_POST_FAILURE: 'CREATE_POST_FAILURE',
  GET_POST_BY_USER_START: 'GET_POST_BY_USER_START',
  GET_POST_BY_USER_SUCCESS: 'GET_POST_BY_USER_SUCCESS',
  GET_POST_BY_USER_FAILURE: 'GET_POST_BY_USER_FAILURE',
  GET_POST_BY_ID_START: 'GET_POST_BY_ID_START',
  GET_POST_BY_ID_SUCCESS: 'GET_POST_BY_ID_SUCCESS',
  GET_POST_BY_ID_FAILURE: 'GET_POST_BY_ID_FAILURE',
  GET_POST_BY_FOLLOWING_START: 'GET_POST_BY_FOLLOWING_START',
  GET_POST_BY_FOLLOWING_SUCCESS: 'GET_POST_BY_FOLLOWING_SUCCESS',
  GET_POST_BY_FOLLOWING_FAILURE: 'GET_POST_BY_FOLLOWING_FAILURE',
};

export default PostActionTypes;
