export const ModalActionTypes = {
  TOGGLE_MODAL_HIDDEN: 'TOGGLE_MODAL_HIDDEN',
  TOGGLE_PROFILE_MODAL_HIDDEN: 'TOGGLE_PROFILE_MODAL_HIDDEN',
  TOGGLE_EDIT_PROFILE_MODAL_HIDDEN: 'TOGGLE_EDIT_PROFILE_MODAL_HIDDEN',
  TOGGLE_COMMENT_MODAL_HIDDEN: 'TOGGLE_COMMENT_MODAL_HIDDEN',
};
