const CommentActionTypes = {
  GET_COMMENTS_BY_POST_ID_START: 'GET_COMMENTS_BY_POST_ID_START',
  GET_COMMENTS_BY_POST_ID_SUCCESS: 'GET_COMMENTS_BY_POST_ID_SUCCESS',
  GET_COMMENTS_BY_POST_ID_FAILURE: 'GET_COMMENTS_BY_POST_ID_FAILURE',
  GET_REPLIES_BY_COMMENT_ID_START: 'GET_REPLIES_BY_COMMENT_ID_START',
  GET_REPLIES_BY_COMMENT_ID_SUCCESS: 'GET_REPLIES_BY_COMMENT_ID_SUCCESS',
  GET_REPLIES_BY_COMMENT_ID_FAILURE: 'GET_REPLIES_BY_COMMENT_ID_FAILURE',
  CREATE_COMMENT_START: 'CREATE_COMMENT_START',
  CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS',
  CREATE_COMMENT_FAILURE: 'CREATE_COMMENT_FAILURE',
  CREATE_REPLY_START: 'CREATE_REPLY_START',
  CREATE_REPLY_SUCCESS: 'CREATE_REPLY_SUCCESS',
  CREATE_REPLY_FAILURE: 'CREATE_REPLY_FAILURE',
};

export default CommentActionTypes;
